title: "cecil.link"
baseline: "Static URL shortener!"
baseurl: https://cecil.local/
description: "Static URL Shortener powered by Cecil."
output:
  formats:
    netlify_redirects:
      mediatype: 'text/plain'
      extension: ''
virtualpages:
  _redirects:
    output: netlify_redirects
  /:
    redirect: https://github.com/Cecilapp/cecil.link
  al:
    redirect: https://arnaudligny.fr
  ggl:
    redirect: https://www.google.com/search?q=cecil+static
