title: "cecil.link"
baseline: "Static URL shortener!"
baseurl: https://cecil.local/
description: "Static URL Shortener powered by Cecil."
output:
  formats:
    netlify_redirects:
      mediatype: 'text/plain'
      extension: ''
    apache_rewrite:
      mediatype: 'text/plain'
      extension: ''
  pagetypeformats:
    homepage: html
defaultpages:
  sitemap:
    published: false
virtualpages:
  - path: _redirects
    output: netlify_redirects
  - path: .htaccess
    output: apache_rewrite
# root domain redirection
  - path: ''
    redirect: https://github.com/Cecilapp/cecil.link
# add URL here
  - path: al
    redirect: https://arnaudligny.fr
  - path: ggl
    redirect: https://www.google.com/search?q=cecil+static
